fixtures:
  forge_modules:
    apt:
      repo: 'puppetlabs/apt'
      ref: '2.2.0'
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.9.0'
    augeasproviders_coree:
      repo: 'herculesteam/augeasproviders_core'
      ref: '2.1.2'
    shellvar:
      repo: 'herculesteam/augeasproviders_shellvar'
      ref: '2.2.0'
  symlinks:
    facette: "#{source_dir}"
